version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database:/var/lib/mysql

  twitch_bot:
    image: python:3.11-bullseye
    container_name: twitch_bot
    build:
      context: twitch_bot
      dockerfile: Dockerfile
    volumes:
      - ./twitch_bot:/app
    depends_on:
      - mysql
    command: python3 -u main.py
